log4j.rootLogger=INFO,stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %m%n
log4j.logger.org.apache.hadoop.ipc.CallQueueManager=warn
log4j.logger.org.apache.hadoop.yarn.client.AMRMClientUtils=warn
log4j.logger.org.apache.hadoop.yarn.client.DefaultNoHARMFailoverProxyProvider=warn
log4j.logger.SecurityLogger.org.apache.hadoop.ipc.Server=warn